# Generated by Django 5.2.4 on 2025-11-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_sale_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
